### ISSUE TITLE
sd convert  to onnx error

### ISSUE THREAD

**Issue by galiiigigi** [Amblyopius/Stable-Diffusion-ONNX-FP16#16] opened 2023-03-22 16:33 UTC
when i convert sd to onnx. There is error and I don't know why.
Here is the error. 
` global_step key not found in model
Traceback (most recent call last):
  File "D:\Stable-Diffusion-ONNX-FP16\conv_sd_to_onnx.py", line 410, in <module>
    pl = load_pipeline_from_original_stable_diffusion_ckpt(
  File "D:\Stable-Diffusion-ONNX-FP16\lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 1078, in load_pipeline_from_original_stable_diffusion_ckpt
    converted_unet_checkpoint = convert_ldm_unet_checkpoint(
  File "D:\Stable-Diffusion-ONNX-FP16\lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 368, in convert_ldm_unet_checkpoint
    new_checkpoint["time_embedding.linear_1.weight"] = unet_state_dict["time_embed.0.weight"]
KeyError: 'time_embed.0.weight'`

**Comment by Amblyopius** [comment] 2023-04-11 16:14
Is it by any chance a LORA rather than a model? Currently no LORA support. You'd have to provide a bit more information about the model for me to know what is going on.

**Comment by ShylockGao** [comment] 2023-05-19 09:11
Looking for help, mine is also reporting an error
`torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::scaled_dot_product_attention' to ONNX opset version 15 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.`

**Comment by Amblyopius** [comment] 2023-06-07 09:09
I'm closing this as the original poster hasn't come back yet. I'm going to assume that was a LORA issue.

Lack of support for scaled_dot_product_attention is caused by running on torch 2.0. Diffusers code doesn't allow turning it off everywhere anymore. As torch 2.1 nightly supports sdp export to ONNX the instructions now exclusively use nightly.

**Closed by Amblyopius** 2023-06-07 09:09 UTC
